/* ===========================
   ICONICSPACE — COMPANY DATA
   156 Organizations Dataset
   =========================== */

const COMPANIES = [
    // ===================== GOVERNMENT AGENCIES =====================
    { name: "NASA", sector: "Government Agency", year: 1958, country: "USA", region: "United States", family: "National Emblem", website: "https://nasa.gov", description: "Dual identity system: the 1959 'Meatball' (blue sphere, red chevron, white stars, orbital ring) and the 1975 'Worm' (Danne & Blackburn minimalist red logotype with removed A-crossbars). The oscillation between these two marks encapsulates the Heritage vs. Modernist tension at the heart of the entire industry's visual culture." },
    { name: "ESA", sector: "Government Agency", year: 1975, country: "France (HQ)", region: "Europe", family: "National Emblem", website: "https://esa.int", description: "Lowercase 'esa' wordmark with blue circular emblem evoking a thumbprint or orbital diagram. Unusually modern and restrained for a government agency. European institutional blue palette." },
    { name: "JAXA", sector: "Government Agency", year: 2003, country: "Japan", region: "Japan", family: "National Emblem", website: "https://jaxa.jp", description: "Clean blue typographic logo with star-from-A motif. Professional, restrained. Japanese institutional restraint applied to space agency branding." },
    { name: "ISRO", sector: "Government Agency", year: 1969, country: "India", region: "India", family: "National Emblem", website: "https://isro.gov.in", description: "Bilingual emblem: Devanagari 'इसरो' (left) + English 'ISRO' (right) in custom 'Prakrta' typeface designed to echo Devanagari letterforms. Saffron/orange color connects to Indian national flag. Rocket motif piercing upward. Performs postcolonial visual placemaking: asserting technological modernity while grounding identity in Sanskrit/Hindi script tradition." },
    { name: "Roscosmos", sector: "Government Agency", year: 1992, country: "Russia", region: "Russia", family: "National Emblem", website: "https://roscosmos.ru", description: "Multiple redesigns reflecting geopolitical identity shifts. Current: red arrow/chevron with blue field. Cyrillic 'РОСКОСМОС' domestically, Latin transliteration internationally. In May 2022, temporarily adopted Red Star logo referencing Soviet victory symbology, explicitly rejecting perceived similarity to Western space agency designs. Three heritage layers: Constructivist geometry, socialist-realist heroic futurism, post-Soviet modernization." },
    { name: "CNSA", sector: "Government Agency", year: 1993, country: "China", region: "China", family: "National Emblem", website: "https://cnsa.gov.cn", description: "Central arrow shape embeds the Chinese character 人 (ren, 'human/people'), expressing the philosophy that humans are the center of space exploration. Three concentric ellipses represent the three cosmic velocities, with the second ring drawn bolder to indicate China's current mastery stage. Deep blue and white palette. CMSA sister emblem uses 中 (zhong, 'China/center') styled as space station silhouette." },
    { name: "MBRSC", sector: "Government Agency", year: 2006, country: "UAE", region: "Middle East", family: "National Emblem", website: "https://mbrsc.ae", description: "Mohammed Bin Rashid Space Centre. Modern, Arabic-influenced design. National prestige branding for UAE's rapidly growing space program." },
    { name: "NSIL", sector: "Government Agency", year: 2019, country: "India", region: "India", family: "National Emblem", website: "https://nsilindia.co.in", description: "NewSpace India Limited. Commercial arm of ISRO. Institutional Indian government branding with space sector overlay." },
    { name: "IN-SPACe", sector: "Government Agency", year: 2020, country: "India", region: "India", family: "National Emblem", website: "https://inspace.gov.in", description: "Indian National Space Promotion and Authorization Centre. Modern institutional logo. Regulatory body for India's emerging commercial space sector." },
    { name: "Arianespace", sector: "Government Agency", year: 1980, country: "France", region: "Europe", family: "Modernist Heritage", website: "https://arianespace.com", description: "Clean, institutional European launch services provider. Blue and white palette. Government-commercial hybrid identity reflecting ESA partnership structure." },
    { name: "AEB", sector: "Government Agency", year: 1994, country: "Brazil", region: "Latin America", family: "National Emblem", website: "https://gov.br/aeb", description: "Agência Espacial Brasileira. Brazilian flag colors (green, gold, blue) directly integrated into circular emblem. Southern Cross constellation motif. Portuguese text. Strongest national flag color integration of any agency in the dataset." },
    { name: "CONAE", sector: "Government Agency", year: 1991, country: "Argentina", region: "Latin America", family: "National Emblem", website: "https://conae.gov.ar", description: "Comisión Nacional de Actividades Espaciales. Argentine blue-and-white (national flag colors). SAOCOM satellite program. Government institutional styling with South American sovereignty assertion." },
    { name: "AEM", sector: "Government Agency", year: 2010, country: "Mexico", region: "Latin America", family: "National Emblem", website: "https://aem.gob.mx", description: "Agencia Espacial Mexicana. Mexican flag colors (green, white, red). Development-focused mandate. Government institutional identity." },
    { name: "AfSA", sector: "Government Agency", year: 2023, country: "Egypt (HQ)", region: "Africa", family: "National Emblem", website: "https://au.int", description: "African Space Agency. Logo selected through continental design competition, won by Remy Fadhil Bouelet, a 22-year-old Cameroonian designer. Unveiled April 2025 at NewSpace Africa Conference in Cairo. Pan-African identity construction from within, rather than importing Western branding agencies. Most distinctive design PROCESS of any space agency." },
    { name: "SANSA", sector: "Government Agency", year: 2010, country: "South Africa", region: "Africa", family: "National Emblem", website: "https://sansa.org.za", description: "South African National Space Agency. Multi-program institutional identity. Earth observation, space science, space operations, space engineering. Post-apartheid South African identity reflected in inclusive, development-oriented branding." },
    { name: "NASRDA", sector: "Government Agency", year: 1999, country: "Nigeria", region: "Africa", family: "National Emblem", website: "https://nasrda.gov.ng", description: "National Space Research and Development Agency. Green/white (Nigerian flag). NigeriaSat program. West African space leadership positioning." },

    // ===================== US LAUNCH =====================
    { name: "SpaceX", sector: "Launch", year: 2002, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://spacex.com", description: "The industry template. Sleek logotype with stylized 'X' trajectory mark in dark blue/black. Ultra-minimalist. Clean. Aggressive. The single most mimicked visual identity in the commercial space sector. Represents the visual shift from NASA heritage to Silicon Valley aesthetics." },
    { name: "Rocket Lab", sector: "Launch", year: 2006, country: "USA/NZ", region: "United States", family: "Tech Disruptor", website: "https://rocketlabusa.com", description: "Dark blue/black wordmark with abstract rocket trajectory icon. Clean sans-serif. Professional small-launch-vehicle aesthetic. Bridges US tech startup and New Zealand engineering cultures." },
    { name: "Relativity Space", sector: "Launch", year: 2015, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://relativityspace.com", description: "Ultra-minimal black wordmark. No icon. Pure typography. Maximum restraint. Signals 3D-printing-as-manufacturing revolution. The absence of visual ornament IS the message." },
    { name: "Stoke Space", sector: "Launch", year: 2019, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://stokespace.com", description: "Lowercase, thin, modern sans-serif. Clean dark palette. Maximum typographic restraint. Fully reusable rocket ambition encoded in the simplicity of the visual identity." },
    { name: "Impulse Space", sector: "Launch", year: 2021, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://impulsespace.com", description: "Clean dark wordmark with abstract propulsion mark. Minimal. In-space transportation focus. SpaceX alumni company with visual DNA inherited from SpaceX's minimalist template." },
    { name: "Firefly Aerospace", sector: "Launch", year: 2014, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://fireflyspace.com", description: "Dark wordmark with stylized firefly/spark icon. Small launch vehicle market. Blue-black palette with subtle warm accent. Bridges heritage and disruptor aesthetics." },
    { name: "ABL Space Systems", sector: "Launch", year: 2017, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://ablspacesystems.com", description: "Bold sans-serif wordmark. Dark. Clean. Responsive launch services positioning. Military-adjacent but startup-presenting." },
    { name: "Astra Space", sector: "Launch", year: 2016, country: "USA", region: "United States", family: "Modernist Heritage", website: "https://astra.com", description: "Bold, wide-tracked uppercase wordmark in blue. Clean institutional feel. References mid-century modernist aerospace typography. Modernist Heritage family exemplar." },

    // ===================== US EARTH OBSERVATION =====================
    { name: "Planet Labs", sector: "Earth Observation", year: 2010, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://planet.com", description: "Clean modern wordmark. Data-forward aesthetic. Earth observation reimagined as tech platform. Blue-toned but distinctly Silicon Valley in execution." },
    { name: "Spire Global", sector: "Earth Observation", year: 2012, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://spire.com", description: "Minimal wordmark with abstract diamond/satellite icon. Space-to-cloud data company. Clean, professional, data-analytics aesthetic rather than traditional aerospace." },
    { name: "BlackSky", sector: "Earth Observation", year: 2014, country: "USA", region: "United States", family: "Defense Professional", website: "https://blacksky.com", description: "Dark, authoritative wordmark. Intelligence/defense-adjacent positioning. Real-time geospatial intelligence. The name itself signals dark, professional, defense-grade capability." },
    { name: "Maxar Technologies", sector: "Earth Observation", year: 1969, country: "USA", region: "United States", family: "Defense Professional", website: "https://maxar.com", description: "Bold corporate sans-serif. Defense/intelligence community standard aesthetic. Earth observation and space infrastructure. Institutional, authoritative." },
    { name: "GHGSat", sector: "Earth Observation", year: 2011, country: "Canada", region: "Other", family: "Sustainability Signaler", website: "https://ghgsat.com", description: "Green accent branding. Emissions monitoring from space. Sustainability signaler: connecting satellite EO directly to environmental accountability." },
    { name: "Pixxel", sector: "Earth Observation", year: 2019, country: "India", region: "India", family: "Tech Disruptor", website: "https://pixxel.space", description: "Modern, vibrant logo. Hyperspectral imaging. Indian startup with Silicon Valley visual language. Purple/blue palette. Pixel-inspired iconography." },

    // ===================== US SATCOM =====================
    { name: "Viasat", sector: "Satellite Communications", year: 1986, country: "USA", region: "United States", family: "Defense Professional", website: "https://viasat.com", description: "Corporate blue institutional wordmark. Defense and commercial satellite communications. Telecommunications visual DNA rather than aerospace." },
    { name: "SES", sector: "Satellite Communications", year: 1985, country: "Luxembourg", region: "Europe", family: "Modernist Heritage", website: "https://ses.com", description: "Clean, bold three-letter wordmark. European satellite operator. Minimal. Institutional. Telecommunications heritage." },
    { name: "OneWeb", sector: "Satellite Communications", year: 2012, country: "UK", region: "Europe", family: "Tech Disruptor", website: "https://oneweb.net", description: "Modern sans-serif with circular satellite constellation icon. LEO broadband. Blue palette. Clean digital-first design." },

    // ===================== US SPACE STATIONS & HABITATS =====================
    { name: "Vast Space", sector: "Space Stations", year: 2021, country: "USA", region: "United States", family: "Modernist Heritage", website: "https://vastspace.com", description: "Brand designed by Manual Creative. Deliberately references 1970s NASA modernism. Dark navy, geometric precision. Custom typeface evoking the Danne & Blackburn era. The most self-conscious exemplar of the Modernist Heritage family." },
    { name: "Axiom Space", sector: "Space Stations", year: 2016, country: "USA", region: "United States", family: "Luxury Experiential", website: "https://axiomspace.com", description: "Premium, fashion-forward branding. Collaboration with Prada for space suit design. Bridges space engineering and luxury fashion. Aspirational, exclusive. Dark with metallic accents." },
    { name: "Sierra Space", sector: "Space Stations", year: 2021, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://sierraspace.com", description: "Clean, modern sans-serif. Dream Chaser spaceplane. Blue-toned. Bridges heritage (Sierra Nevada Corp. parent) and startup aesthetics." },
    { name: "Orbital Reef", sector: "Space Stations", year: 2021, country: "USA", region: "United States", family: "Modernist Heritage", website: "https://orbitalreef.com", description: "Blue Origin/Sierra Space joint venture. Clean, institutional blue. Space station as commercial destination. Modernist heritage with hospitality overtones." },
    { name: "Nanoracks", sector: "Space Stations", year: 2009, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://nanoracks.com", description: "Modern sans-serif with abstract icon. Space station services. Commercial space infrastructure. Pioneer of in-orbit services." },

    // ===================== US SPACE TOURISM =====================
    { name: "Virgin Galactic", sector: "Space Tourism", year: 2004, country: "USA/UK", region: "United States", family: "Luxury Experiential", website: "https://virgingalactic.com", description: "Purple-pink gradients. The 'Iris' eye-like icon. Lifestyle branding derived from Virgin Group DNA. The most visually distinctive space tourism brand: aspirational, experiential, fashion-adjacent. Deliberately avoids aerospace visual codes." },
    { name: "Blue Origin", sector: "Space Tourism", year: 2000, country: "USA", region: "United States", family: "Modernist Heritage", website: "https://blueorigin.com", description: "Feather icon + clean sans-serif wordmark. Blue palette (obviously). The feather represents the perfection of flight. Bridges heritage engineering (Bezos 'Day One' philosophy) with accessible tourism branding." },
    { name: "Space Perspective", sector: "Space Tourism", year: 2019, country: "USA", region: "United States", family: "Luxury Experiential", website: "https://spaceperspective.com", description: "Warm, lifestyle-oriented aesthetic. 'Gentle' space tourism via stratospheric balloon. Earth-toned palette. Hospitality visual language. Deliberately gentle and human rather than technical and cold." },
    { name: "World View", sector: "Space Tourism", year: 2012, country: "USA", region: "United States", family: "Luxury Experiential", website: "https://worldview.space", description: "Stratospheric ballooning. Sunset gradients, experiential warmth. Photography-forward branding emphasizing the view, not the vehicle." },

    // ===================== US DEBRIS REMOVAL / ISAM =====================
    { name: "Astroscale", sector: "Debris Removal", year: 2013, country: "Japan/UK", region: "Japan", family: "Sustainability Signaler", website: "https://astroscale.com", description: "Clean modern branding with sustainability messaging integrated. Debris removal pioneer. Blue-teal palette. Japanese-founded but globally branded. Sustainability signaler with tech disruptor execution." },
    { name: "ClearSpace", sector: "Debris Removal", year: 2018, country: "Switzerland", region: "Europe", family: "Sustainability Signaler", website: "https://clearspace.today", description: "Green branding. ESA-contracted debris removal. Swiss precision meets environmental responsibility. The name itself signals the mission: clearing space." },
    { name: "Orbit Fab", sector: "Debris Removal", year: 2018, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://orbitfab.com", description: "In-space refueling. Industrial orange/dark palette. 'Gas stations in space' positioning. Deliberately industrial rather than sleek." },

    // ===================== US IN-SPACE MANUFACTURING =====================
    { name: "Varda Space Industries", sector: "Manufacturing", year: 2020, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://varda.com", description: "Modernist sans-serif with abstract crystallographic icon. In-space pharmaceutical manufacturing. Dark palette. Clean, precise, scientific." },
    { name: "Space Forge", sector: "Manufacturing", year: 2018, country: "UK", region: "Europe", family: "Sustainability Signaler", website: "https://spaceforge.co.uk", description: "Manufacturing in microgravity with 'zero-waste' messaging. Green/sustainability accents. Welsh space startup. Environmental themes in branding." },
    { name: "Redwire Space", sector: "Manufacturing", year: 2020, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://redwirespace.com", description: "Bold red and dark palette. In-space manufacturing and infrastructure. The red color is distinctive in a blue-dominated field. Aggressive, confident." },
    { name: "AstroForge", sector: "Manufacturing", year: 2022, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://astroforge.com", description: "Asteroid mining startup. Dark, bold wordmark. Industrial/forge metaphor. Aggressive Silicon Valley aesthetic applied to resource extraction." },
    { name: "Made In Space", sector: "Manufacturing", year: 2010, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://madeinspace.us", description: "Now part of Redwire. Clean wordmark. 3D printing in microgravity pioneer. The name IS the brand: manufacturing relocated to orbit." },

    // ===================== US PROPULSION =====================
    { name: "Ursa Major", sector: "Launch", year: 2015, country: "USA", region: "United States", family: "Modernist Heritage", website: "https://ursamajor.com", description: "Branding by Hoo Koo E Koo. Bold, clean, monochromatic. Rocket engine manufacturer. Astronomical reference (constellation). Heritage-meets-modern execution." },
    { name: "Launcher", sector: "Launch", year: 2017, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://launcherspace.com", description: "Now part of Vast. Clean sans-serif. Engine and vehicle development. Minimal, direct, functional naming and branding." },

    // ===================== US DEFENSE =====================
    { name: "True Anomaly", sector: "Defense", year: 2022, country: "USA", region: "United States", family: "Defense Professional", website: "https://trueanomaly.com", description: "Named after an orbital mechanics term. Rebranded by Kontrapunkt. Uses the Greek letter Nu (ν) as icon. Space domain awareness for defense. Sleek but authoritative. The orbital mechanics name signals insider knowledge." },
    { name: "Slingshot Aerospace", sector: "Defense", year: 2017, country: "USA", region: "United States", family: "Defense Professional", website: "https://slingshotaerospace.com", description: "Space situational awareness. Clean, professional. Blue-dark palette. Military/intelligence positioning with tech execution." },

    // ===================== US LUNAR & PLANETARY =====================
    { name: "Intuitive Machines", sector: "Launch", year: 2013, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://intuitivemachines.com", description: "Clean corporate sans-serif. Lunar lander services (CLPS). Blue palette. Bridges NASA heritage (Houston) with modern startup aesthetic." },
    { name: "Astrobotic", sector: "Launch", year: 2007, country: "USA", region: "United States", family: "Modernist Heritage", website: "https://astrobotic.com", description: "Lunar delivery services. Clean blue/white. NASA CLPS contractor. Pittsburgh/Carnegie Mellon heritage. Institutional but modern." },
    { name: "ispace", sector: "Launch", year: 2010, country: "Japan", region: "Japan", family: "Tech Disruptor", website: "https://ispace-inc.com", description: "Pure black wordmark. Ultra-minimal. Japanese monochrome minimalism exemplar. Lunar exploration. Lowercase 'ispace' signals tech startup, not aerospace heritage. Maximum restraint." },
    // ===================== LEGACY AEROSPACE PRIMES =====================
    { name: "Boeing", sector: "Legacy Aerospace", year: 1916, country: "USA", region: "United States", family: "Modernist Heritage", website: "https://boeing.com", description: "Iconic logotype with stylized globe/orbit symbol. One of the few space companies using a design with deep heritage continuity. Multiple logo evolution cycles reflecting corporate identity shifts." },
    { name: "Lockheed Martin", sector: "Legacy Aerospace", year: 1995, country: "USA", region: "United States", family: "Defense Professional", website: "https://lockheedmartin.com", description: "Star-in-circle icon. Dark blue. Defense-grade sobriety and authority. The merger of Lockheed and Martin Marietta created a visual identity that is the archetype of Defense Professional: reliable, institutional, serious." },
    { name: "Northrop Grumman", sector: "Legacy Aerospace", year: 1994, country: "USA", region: "United States", family: "Defense Professional", website: "https://northropgrumman.com", description: "Bold wordmark with chevron-star emblem. Corporate blue and white. Authoritative. Defense-industrial complex visual standard. Heritage engineering institution." },
    { name: "L3Harris Technologies", sector: "Legacy Aerospace", year: 2019, country: "USA", region: "United States", family: "Defense Professional", website: "https://l3harris.com", description: "Clean uppercase sans-serif. Blue and grey. Institutional authority. Defense electronics and space systems. Merger identity combining two heritage companies." },
    { name: "Raytheon Technologies", sector: "Legacy Aerospace", year: 2020, country: "USA", region: "United States", family: "Defense Professional", website: "https://rtx.com", description: "Now RTX. Bold corporate sans-serif. Blue. Defense-industrial visual template. Massive conglomerate identity." },
    { name: "BAE Systems", sector: "Legacy Aerospace", year: 1999, country: "UK", region: "Europe", family: "Defense Professional", website: "https://baesystems.com", description: "Red and grey. British defense heritage. Shield/crest-adjacent branding. European defense-professional aesthetic." },
    { name: "Airbus", sector: "Legacy Aerospace", year: 1970, country: "France/Germany", region: "Europe", family: "Modernist Heritage", website: "https://airbus.com", description: "Clean blue wordmark. European aerospace giant. Airbus Defence and Space division. Institutional, modern, pan-European identity." },
    { name: "Thales Alenia Space", sector: "Legacy Aerospace", year: 2007, country: "France/Italy", region: "Europe", family: "Modernist Heritage", website: "https://thalesaleniaspace.com", description: "Blue corporate identity. European satellite and space systems manufacturer. Joint French-Italian heritage. Clean institutional styling." },
    { name: "OHB", sector: "Legacy Aerospace", year: 1981, country: "Germany", region: "Europe", family: "Modernist Heritage", website: "https://ohb.de", description: "German space company. Blue and white. European medium-size aerospace. Institutional, restrained, precision-engineering aesthetic." },
    { name: "AVIO", sector: "Legacy Aerospace", year: 1912, country: "Italy", region: "Europe", family: "Modernist Heritage", website: "https://avio.com", description: "Italian aerospace propulsion. Vega launcher manufacturer. Heritage Italian engineering identity. Blue/dark palette." },
    { name: "Kongsberg", sector: "Legacy Aerospace", year: 1814, country: "Norway", region: "Europe", family: "Modernist Heritage", website: "https://kongsberg.com", description: "Oldest company in the dataset (founded 1814). Norwegian defense and aerospace. Clean, Scandinavian-influenced design. Blue institutional palette." },
    { name: "Saab", sector: "Legacy Aerospace", year: 1937, country: "Sweden", region: "Europe", family: "Defense Professional", website: "https://saab.com", description: "Swedish defense and aerospace. Griffin heraldic icon. Distinctive Nordic defense branding. Blue with heritage crest element." },
    { name: "GMV", sector: "Legacy Aerospace", year: 1984, country: "Spain", region: "Europe", family: "Modernist Heritage", website: "https://gmv.com", description: "Spanish technology company. Space sector focus. Blue corporate identity. European institutional styling." },
    { name: "Telespazio", sector: "Legacy Aerospace", year: 1961, country: "Italy", region: "Europe", family: "Modernist Heritage", website: "https://telespazio.com", description: "Italian space services. Leonardo/Thales joint venture. Blue. European satellite operations heritage." },

    // ===================== US GROUND SEGMENT & DOWNSTREAM =====================
    { name: "Kratos Defense", sector: "Defense", year: 1994, country: "USA", region: "United States", family: "Defense Professional", website: "https://kratosdefense.com", description: "Dark blue. Defense professional. Satellite ground systems. Military/intelligence community visual template." },
    { name: "ATLAS Space Operations", sector: "Other", year: 2015, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://atlasground.com", description: "Ground-station-as-a-service. Clean modern branding. Software-defined ground network. Tech disruptor visual language applied to ground segment." },
    { name: "Leaf Space", sector: "Other", year: 2014, country: "Italy", region: "Europe", family: "Sustainability Signaler", website: "https://leaf.space", description: "The name 'Leaf' signals sustainability. Ground station network. Green accent. European clean-tech positioning." },

    // ===================== US SATELLITE MANUFACTURING =====================
    { name: "York Space Systems", sector: "Satellite Manufacturing", year: 2015, country: "USA", region: "United States", family: "Defense Professional", website: "https://yorkspacesystems.com", description: "Professional, restrained, defense-adjacent. Standard bus satellite manufacturer. Clean sans-serif. Blue-dark palette. Military-grade reliability signaling." },
    { name: "Terran Orbital", sector: "Satellite Manufacturing", year: 2013, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://terranorbital.com", description: "Now part of Lockheed Martin. Small satellite manufacturer. Clean tech-forward branding. Dark palette." },
    { name: "Capella Space", sector: "Earth Observation", year: 2016, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://capellaspace.com", description: "SAR satellite company. Clean, modern. Dark palette with blue accent. Data-forward positioning. Star-name reference (Capella)." },
    { name: "Muon Space", sector: "Earth Observation", year: 2021, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://muonspace.com", description: "Climate-focused satellite constellation. Clean, modern. Physics particle name. Sustainability-adjacent but tech disruptor execution." },
    { name: "Loft Orbital", sector: "Satellite Manufacturing", year: 2017, country: "USA/France", region: "United States", family: "Tech Disruptor", website: "https://loftorbital.com", description: "Space-as-a-service. Clean, modern branding. Software-defined satellite approach. Startup aesthetic with Franco-American heritage." },

    // ===================== SPACE FINANCE & ADVISORY =====================
    { name: "Space Capital", sector: "Other", year: 2018, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://spacecapital.com", description: "VC fund. Clean, minimal. Dark palette. Finance visual language with space sector specialization. The logo must appeal to both space founders and institutional investors." },
    { name: "Seraphim Space", sector: "Other", year: 2006, country: "UK", region: "Europe", family: "Tech Disruptor", website: "https://seraphim.vc", description: "Space-focused VC. Clean modern branding. Angular mark. Investment-grade visual presentation with space sector focus." },

    // ===================== LASER / COMMS =====================
    { name: "Mynaric", sector: "Other", year: 2009, country: "Germany", region: "Europe", family: "Tech Disruptor", website: "https://mynaric.com", description: "Laser communications. Clean blue wordmark. German precision engineering meets tech startup aesthetic. Defense and commercial applications." },

    // ===================== JAPAN =====================
    { name: "Synspective", sector: "Earth Observation", year: 2018, country: "Japan", region: "Japan", family: "Tech Disruptor", website: "https://synspective.com", description: "Clean monochrome. SAR satellite company. Japanese monochrome minimalism. Restrained, precise, maximum negative space." },
    { name: "Axelspace", sector: "Satellite Manufacturing", year: 2008, country: "Japan", region: "Japan", family: "Tech Disruptor", website: "https://axelspace.com", description: "Black and white. Microsatellite manufacturer. Japanese design restraint. Clean, geometric, minimal." },
    { name: "iQPS", sector: "Earth Observation", year: 2005, country: "Japan", region: "Japan", family: "Tech Disruptor", website: "https://i-qps.net", description: "Clean monochromatic. Small SAR satellite developer. Kyushu University spinoff. Japanese institutional restraint." },
    { name: "Astroscale Japan", sector: "Debris Removal", year: 2013, country: "Japan", region: "Japan", family: "Sustainability Signaler", website: "https://astroscale.com", description: "Japanese headquarters of global debris removal company. Clean, sustainability-forward. Blue-teal palette." },
    { name: "Space One", sector: "Launch", year: 2018, country: "Japan", region: "Japan", family: "Tech Disruptor", website: "https://space-one.co.jp", description: "Canon Electronics-backed launch startup. Clean, professional. Japanese corporate restraint applied to launch sector." },
    { name: "Interstellar Technologies", sector: "Launch", year: 2003, country: "Japan", region: "Japan", family: "Tech Disruptor", website: "https://istellartech.com", description: "Hokkaido-based launch startup. Clean modern branding. One of Japan's earliest private rocket companies." },

    // ===================== SOUTH KOREA =====================
    { name: "Perigee Aerospace", sector: "Launch", year: 2018, country: "South Korea", region: "South Korea", family: "Tech Disruptor", website: "https://perigee.kr", description: "Korean small launch vehicle developer. Clean, modern. Blue-dark palette. Orbital mechanics-inspired naming." },
    { name: "Satrec Initiative", sector: "Satellite Manufacturing", year: 1999, country: "South Korea", region: "South Korea", family: "Modernist Heritage", website: "https://satreci.com", description: "Korean satellite manufacturer. KAIST spinoff. Institutional/academic heritage. Professional blue branding." },

    // ===================== INDIA (COMMERCIAL) =====================
    { name: "Skyroot Aerospace", sector: "Launch", year: 2018, country: "India", region: "India", family: "Tech Disruptor", website: "https://skyroot.in", description: "India's first private rocket company. Clean modern branding. Dark palette. Silicon Valley visual language adopted by Indian startup. 'Vikram' rocket series (named after Vikram Sarabhai)." },
    { name: "Agnikul Cosmos", sector: "Launch", year: 2017, country: "India", region: "India", family: "Tech Disruptor", website: "https://agnikul.in", description: "3D-printed rocket engines. Clean, modern branding. Blue/dark palette. IIT Madras spinoff. Indian deep-tech with global visual aspirations. 'Agni' means fire in Sanskrit." },
    { name: "Dhruva Space", sector: "Satellite Manufacturing", year: 2012, country: "India", region: "India", family: "Tech Disruptor", website: "https://dhruvaspace.com", description: "Satellite platforms and ground systems. 'Dhruva' means Pole Star in Sanskrit. Clean, modern. Indian commercial space with global visual positioning." },
    { name: "GalaxEye Space", sector: "Earth Observation", year: 2020, country: "India", region: "India", family: "Tech Disruptor", website: "https://galaxeye.space", description: "Multi-sensor satellite fusion. IIT Madras spinoff. Modern, vibrant branding. Purple/blue palette. Indian deep-tech startup aesthetic." },
    { name: "SatSure", sector: "Earth Observation", year: 2017, country: "India", region: "India", family: "Tech Disruptor", website: "https://satsure.co", description: "Satellite data analytics for agriculture and finance. Green-teal accents. Data/AI-forward. Indian agritech-meets-space positioning." },
    { name: "Kawa Space", sector: "Earth Observation", year: 2021, country: "India", region: "India", family: "Tech Disruptor", website: "https://kawa.space", description: "Sub-meter resolution EO. Clean, modern. Bold branding. Indian commercial EO startup with global ambitions." },
    { name: "Manastu Space", sector: "Launch", year: 2017, country: "India", region: "India", family: "Sustainability Signaler", website: "https://manastuspace.com", description: "Green propulsion systems. Environmental themes in branding. 'Manastu' = 'atmosphere' in Sanskrit. Sustainability signaler through both naming and visual identity. The only Indian space startup in this family." },
    { name: "Digantara", sector: "Other", year: 2018, country: "India", region: "India", family: "Tech Disruptor", website: "https://digantara.com", description: "Space situational awareness. Clean modern branding. 'Digantara' means 'horizon' in Sanskrit. Indian SSA startup." },

    // ===================== CHINA (COMMERCIAL) =====================
    { name: "Galactic Energy", sector: "Launch", year: 2018, country: "China", region: "China", family: "Tech Disruptor", website: "https://www.galactic-energy.cn", description: "银河动力 (Yinhe Dongli). Bilingual blue/silver. Ceres-1 rocket. Chinese commercial launch startup with global visual positioning." },
    { name: "LandSpace", sector: "Launch", year: 2015, country: "China", region: "China", family: "Tech Disruptor", website: "https://landspace.com", description: "蓝箭航天 (Lanjian Hangtian, 'Blue Arrow'). Bilingual. Blue dominant. Zhuque-2 (methane rocket). The English name and visual identity closely follow Western templates." },
    { name: "CAS Space", sector: "Launch", year: 2018, country: "China", region: "China", family: "Tech Disruptor", website: "https://www.cas-space.com", description: "中科宇航 (Zhongke Yuhang). Chinese Academy of Sciences lineage. Bilingual logo. Blue/white institutional palette. State-academic-commercial hybrid. The CAS brand provides institutional legitimacy." },
    { name: "Orienspace", sector: "Launch", year: 2020, country: "China", region: "China", family: "Tech Disruptor", website: "https://www.orienspace.com", description: "东方空间 (Dongfang Kongjian, 'Eastern Space'). Professional design-firm-created visual identity system. Blue/dark. Gravity-1 sea-launch rocket. Cultural name reference to 'East' (Orient)." },
    { name: "Galaxy Space", sector: "Satellite Communications", year: 2018, country: "China", region: "China", family: "Tech Disruptor", website: "https://www.galaxyspace.cn", description: "银河航天 (Yinhe Hangtian). LEO broadband constellation. Bilingual. Blue/silver. Chinese Starlink analogue. Clean corporate visual identity." },
    { name: "Spacety", sector: "Satellite Manufacturing", year: 2016, country: "China", region: "China", family: "Tech Disruptor", website: "https://www.spacety.com", description: "天仪研究院 (Tianyi Yanjiuyuan, 'Heavenly Instrument Research Institute'). Research-institute-derived identity. Bilingual. Blue/white. Clean modern styling." },
    { name: "OneSpace", sector: "Launch", year: 2015, country: "China", region: "China", family: "Tech Disruptor", website: "https://www.onespacechina.com", description: "零壹空间 (Lingyi Kongjian, 'Zero-One Space'). One of China's earliest commercial launch startups. Bilingual. Blue/dark. OS-X rocket series." },

    // ===================== RUSSIA =====================
    { name: "Gazprom Space Systems", sector: "Satellite Communications", year: 1992, country: "Russia", region: "Russia", family: "Defense Professional", website: "https://gazprom-spacesystems.ru", description: "Gazprom subsidiary. Russian state energy giant extending into space. Corporate blue. Russian oligarchic-state capitalism reflected in branding that combines Gazprom corporate DNA with space sector overlay." },
    // ===================== LATIN AMERICA =====================
    { name: "INPE", sector: "Government Agency", year: 1961, country: "Brazil", region: "Latin America", family: "National Emblem", website: "https://inpe.br", description: "Instituto Nacional de Pesquisas Espaciais. Brazilian space research institute. Blue/white institutional palette. Academic/research identity. Portuguese text." },
    { name: "Alcantara Space Center", sector: "Other", year: 1990, country: "Brazil", region: "Latin America", family: "National Emblem", website: "https://fab.mil.br", description: "Brazilian equatorial spaceport. Military institutional identity (Brazilian Air Force). National flag colors. Launch infrastructure rather than company brand." },
    { name: "Visiona", sector: "Satellite Manufacturing", year: 2012, country: "Brazil", region: "Latin America", family: "Modernist Heritage", website: "https://visionaespacial.com.br", description: "Visiona Tecnologia Espacial. Brazilian satellite systems integrator. Embraer/Telebras joint venture. Blue/white corporate. State-private hybrid with Brazilian institutional DNA." },
    { name: "INVAP", sector: "Satellite Manufacturing", year: 1976, country: "Argentina", region: "Latin America", family: "Modernist Heritage", website: "https://invap.com.ar", description: "Argentine state-owned technology company. Full-cycle satellite capability (SAOCOM). Blue/grey institutional. One of the few Latin American entities with end-to-end space manufacturing capability." },

    // ===================== AFRICA (beyond agencies) =====================
    { name: "Kenya Space Agency", sector: "Government Agency", year: 2017, country: "Kenya", region: "Africa", family: "National Emblem", website: "https://ksa.go.ke", description: "Clean institutional identity. Sustainable development focus. Kenyan national colors. East African space leadership positioning." },
    { name: "Rwanda Space Agency", sector: "Government Agency", year: 2020, country: "Rwanda", region: "Africa", family: "National Emblem", website: "https://space.gov.rw", description: "'Digital nation' positioning. Tech-forward government. One of Africa's newest space agencies. Clean, modern institutional identity reflecting Rwanda's innovation branding." },
    // ===================== ADDITIONAL COMPANIES =====================
    { name: "K2 Space", sector: "Satellite Manufacturing", year: 2022, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://k2space.com", description: "Bold, simple. Two characters, maximum impact. Large satellite platforms. Dark palette. SpaceX alumni. Extreme minimalism: the name and logo are reduced to bare essentials." },
    { name: "Momentus", sector: "Launch", year: 2017, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://momentus.space", description: "Branding by Cosma Schema. In-space transportation. Clean sans-serif with orbital icon. Dark palette. Water-plasma propulsion." },
    { name: "D-Orbit", sector: "Launch", year: 2011, country: "Italy", region: "Europe", family: "Tech Disruptor", website: "https://dorbit.space", description: "Italian in-orbit transportation and logistics. ION Satellite Carrier. Clean, modern European startup branding. Dark with accent color." },
    { name: "Exolaunch", sector: "Launch", year: 2017, country: "Germany", region: "Europe", family: "Tech Disruptor", website: "https://exolaunch.com", description: "German rideshare and deployment services. Clean, modern. Blue/dark. European NewSpace visual template." },
    { name: "Phantom Space", sector: "Launch", year: 2019, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://phantomspace.com", description: "Small launch vehicle developer. Dark, bold. 'Phantom' name evokes stealth/mystery. Arizona-based." },
    { name: "Gilmour Space", sector: "Launch", year: 2012, country: "Australia", region: "Other", family: "Tech Disruptor", website: "https://gilmourspace.com", description: "Australian launch startup. Eris rocket. Clean modern branding. Southern Hemisphere launch provider with global visual positioning." },
    { name: "Orbit Fab", sector: "Manufacturing", year: 2018, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://orbitfab.com", description: "In-space refueling ('gas stations in space'). Industrial orange accent on dark palette. Deliberately utilitarian rather than sleek." },
    { name: "SpaceLink", sector: "Satellite Communications", year: 2020, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://spacelink.com", description: "Data relay satellite network. Clean, corporate. Blue palette. Communications infrastructure branding." },
    { name: "Lynk Global", sector: "Satellite Communications", year: 2017, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://lynk.world", description: "Satellite-to-phone connectivity. Modern, consumer-facing. Blue with warm accents. Bridges satellite and mobile telecom aesthetics." },
    { name: "AST SpaceMobile", sector: "Satellite Communications", year: 2017, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://ast-science.com", description: "Space-based cellular broadband. Clean modern branding. Purple/blue. Mobile-first positioning. Consumer-facing aspiration." },
    { name: "Sidus Space", sector: "Satellite Manufacturing", year: 2012, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://sidusspace.com", description: "AI-enabled satellite manufacturing. Clean, modern. Purple accent. Florida-based. 'Sidus' means star in Latin." },
    { name: "Satellogic", sector: "Earth Observation", year: 2010, country: "Argentina", region: "Latin America", family: "Tech Disruptor", website: "https://satellogic.com", description: "Argentine EO constellation. Clean, modern. One of the few Latin American commercial space companies with global visual positioning. Blue/dark." },
    { name: "HawkEye 360", sector: "Earth Observation", year: 2015, country: "USA", region: "United States", family: "Defense Professional", website: "https://he360.com", description: "RF analytics from space. Defense/intelligence positioning. Dark, professional. Bird-of-prey naming evokes surveillance capability." },
    { name: "Umbra", sector: "Earth Observation", year: 2015, country: "USA", region: "United States", family: "Modernist Heritage", website: "https://umbra.space", description: "SAR satellite company. Custom fonts: 'Transducer' and 'Space Grotesk'. Heritage engineering meets digital precision. Modernist Heritage exemplar." },
    { name: "Orbital Insight", sector: "Earth Observation", year: 2013, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://orbitalinsight.com", description: "Geospatial analytics platform. Blue. Data/AI company aesthetic rather than satellite company. Silicon Valley DNA." },
    { name: "Orbital Assembly", sector: "Space Stations", year: 2019, country: "USA", region: "United States", family: "Luxury Experiential", website: "https://orbitalassembly.com", description: "Space hotel concepts. Voyager Station. Hospitality-industry visual language. Aspirational, experiential. Future-luxury positioning." },
    { name: "SpinLaunch", sector: "Launch", year: 2014, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://spinlaunch.com", description: "Kinetic launch system. Bold, dynamic branding. Spinning/rotational iconography. Orange/dark. One of the few companies whose logo directly references its technology." },
    { name: "Stratolaunch", sector: "Launch", year: 2011, country: "USA", region: "United States", family: "Modernist Heritage", website: "https://stratolaunch.com", description: "Hypersonic vehicle launch from carrier aircraft. Clean, professional. Blue/white. Paul Allen heritage. Aviation-adjacent branding." },
    { name: "Aerojet Rocketdyne", sector: "Launch", year: 1942, country: "USA", region: "United States", family: "Modernist Heritage", website: "https://rocket.com", description: "Now part of L3Harris. Heritage propulsion manufacturer. Decades of logo evolution. Classic aerospace institutional identity." },
    { name: "Voyager Space", sector: "Space Stations", year: 2019, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://voyagerspace.com", description: "Space station and exploration holding company. Clean, modern. Dark palette. Exploration-as-brand. Acquires and consolidates space companies." },
    { name: "Intelsat", sector: "Satellite Communications", year: 1964, country: "USA", region: "United States", family: "Modernist Heritage", website: "https://intelsat.com", description: "Oldest commercial satellite operator. Blue. Heritage telecommunications identity. Multiple logo evolutions reflecting industry transitions." },
    { name: "Telesat", sector: "Satellite Communications", year: 1969, country: "Canada", region: "Other", family: "Modernist Heritage", website: "https://telesat.com", description: "Canadian satellite operator. Lightspeed LEO constellation. Blue corporate. Telecommunications heritage identity." },
    { name: "Eutelsat", sector: "Satellite Communications", year: 1977, country: "France", region: "Europe", family: "Modernist Heritage", website: "https://eutelsat.com", description: "European satellite operator. Now merged with OneWeb. Blue institutional. European telecommunications heritage." },
    { name: "Iridium", sector: "Satellite Communications", year: 1998, country: "USA", region: "United States", family: "Modernist Heritage", website: "https://iridium.com", description: "Global satellite phone network. Clean, modern post-bankruptcy rebrand. Blue/white. The name references the element with 77 electrons, matching the original 77-satellite constellation plan." },
    { name: "EOS Data Analytics", sector: "Earth Observation", year: 2015, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://eos.com", description: "Agricultural satellite analytics. Green accent. Data platform aesthetic. Sustainability-adjacent through agricultural application." },
    { name: "Iceye", sector: "Earth Observation", year: 2014, country: "Finland", region: "Europe", family: "Tech Disruptor", website: "https://iceye.com", description: "Finnish SAR satellite company. Clean, modern. Dark/blue. Nordic minimalism applied to satellite EO. European NewSpace." },
    { name: "Tomorrow.io", sector: "Earth Observation", year: 2016, country: "USA/Israel", region: "United States", family: "Tech Disruptor", website: "https://tomorrow.io", description: "Weather intelligence platform with own satellite constellation. Warm, consumer-facing branding. Orange/teal. Tech startup aesthetic applied to weather." },
    { name: "Wyvern", sector: "Earth Observation", year: 2018, country: "Canada", region: "Other", family: "Tech Disruptor", website: "https://wyvern.space", description: "Canadian hyperspectral EO. Mythical creature naming. Purple/dark. Bold, distinctive in a blue-dominated field." },
    { name: "UP42", sector: "Other", year: 2019, country: "Germany", region: "Europe", family: "Tech Disruptor", website: "https://up42.com", description: "Geospatial data marketplace. Airbus subsidiary. Clean, platform-style branding. Developer-facing aesthetic." },
    { name: "Kayhan Space", sector: "Other", year: 2018, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://kayhan.space", description: "Space traffic management. Clean, modern. Persian-name reference. Blue/dark. SSA sector visual template." },
    { name: "LeoLabs", sector: "Other", year: 2016, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://leolabs.space", description: "Space environment monitoring. Radar tracking network. Clean, data-forward. Blue/dark. SSA sector." },
    { name: "CesiumAstro", sector: "Satellite Communications", year: 2017, country: "USA", region: "United States", family: "Defense Professional", website: "https://cesiumastro.com", description: "Phased array communications. Defense-adjacent. Clean, professional. Blue. Element-name reference (Cesium)." },
    { name: "Albedo", sector: "Earth Observation", year: 2020, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://albedo.com", description: "Very-low-Earth-orbit imagery. Clean, modern. Physics term naming (albedo = reflectivity). Dark palette." },
    { name: "Epsilon3", sector: "Other", year: 2021, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://epsilon3.io", description: "Mission operations software. Clean, software-company aesthetic. Math/physics naming. Developer-facing." },
    { name: "Phantom Space", sector: "Launch", year: 2019, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://phantomspace.com", description: "Small launch vehicle. Dark, bold. Arizona-based. 'Phantom' evokes stealth capability." },
    { name: "Dawn Aerospace", sector: "Launch", year: 2017, country: "New Zealand", region: "Other", family: "Sustainability Signaler", website: "https://dawnaerospace.com", description: "Reusable suborbital vehicle. Clean, warm. Green/sustainable accents. New Zealand-Netherlands dual heritage. Dawn = new beginning." },
    { name: "PLD Space", sector: "Launch", year: 2011, country: "Spain", region: "Europe", family: "Tech Disruptor", website: "https://pldspace.com", description: "Spanish launch startup. Miura rockets. Clean, modern. Blue/white. European NewSpace with Spanish institutional backing." },
    { name: "Isar Aerospace", sector: "Launch", year: 2018, country: "Germany", region: "Europe", family: "Tech Disruptor", website: "https://isaraerospace.com", description: "German launch startup. Spectrum rocket. Clean, minimal. Blue/dark. Munich-based. River Isar naming = local identity." },
    { name: "RFA", sector: "Launch", year: 2018, country: "Germany", region: "Europe", family: "Tech Disruptor", website: "https://rfa.space", description: "Rocket Factory Augsburg. Bold sans-serif. German industrial naming. Blue/dark. Manufacturing-forward identity." },
    { name: "Skyrora", sector: "Launch", year: 2017, country: "UK", region: "Europe", family: "Tech Disruptor", website: "https://skyrora.com", description: "Scottish launch company. Clean, modern. Blue/white. UK NewSpace. Celtic-inspired naming." },
    { name: "Open Cosmos", sector: "Satellite Manufacturing", year: 2015, country: "UK", region: "Europe", family: "Tech Disruptor", website: "https://open-cosmos.com", description: "End-to-end satellite missions. Clean, modern. Blue/white. 'Open' signals accessibility and democratization." },
    { name: "Surrey Satellite", sector: "Satellite Manufacturing", year: 1985, country: "UK", region: "Europe", family: "Modernist Heritage", website: "https://sstl.co.uk", description: "University of Surrey spinoff. Pioneer of small satellites. Blue institutional. British academic heritage. Now Airbus subsidiary." },
    { name: "EnduroSat", sector: "Satellite Manufacturing", year: 2015, country: "Bulgaria", region: "Europe", family: "Tech Disruptor", website: "https://endurosat.com", description: "Bulgarian microsatellite company. Clean, modern. Dark. Eastern European NewSpace. Unexpected origin for space startup." },
    { name: "Sateliot", sector: "Satellite Communications", year: 2018, country: "Spain", region: "Europe", family: "Tech Disruptor", website: "https://sateliot.space", description: "Spanish IoT satellite constellation. Clean, playful. Blue/purple. 5G NB-IoT from space." },
    { name: "Spire Aviation", sector: "Other", year: 2020, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://spire.com", description: "Aviation analytics division of Spire Global. ADS-B from space. Data-forward. Clean, analytical aesthetic." },
    { name: "Privateer", sector: "Other", year: 2021, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://privateer.com", description: "Space sustainability data. Steve Wozniak-founded. Dark, bold. Nautical naming (pirate reference). Counter-culture Silicon Valley positioning." },
    { name: "Turion Space", sector: "Debris Removal", year: 2020, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://turionspace.com", description: "In-space logistics and debris removal. Dark, minimal. Chess-piece naming (turion). SpaceX-influenced visual DNA." }
];
