const EXPANSION_5 = [
    { name: "EnvisionTEC Space", sector: "Mission Program", year: 2032, country: "EU", region: "Europe", family: "National Emblem", website: "https://esa.int", description: "ESA Venus orbiter mission (planned 2031 launch). Radar and spectrometer mapping of Venus surface and atmosphere. Blue ESA institutional. The European return to Venus after Venus Express." },
    { name: "Hera Mission", sector: "Mission Program", year: 2024, country: "EU", region: "Europe", family: "National Emblem", website: "https://esa.int", description: "ESA planetary defense mission. Follow-up to NASA's DART impact. Named after the Greek goddess. Will study the Didymos-Dimorphos binary asteroid system. ESA's first planetary defense contribution." },
    { name: "Comet Interceptor", sector: "Mission Program", year: 2029, country: "EU/Japan", region: "Europe", family: "National Emblem", website: "https://esa.int", description: "ESA/JAXA mission to intercept a long-period comet or interstellar object. Three-spacecraft formation. The first mission designed to wait for its target. ESA/JAXA joint identity." },
    { name: "PLATO Mission", sector: "Mission Program", year: 2026, country: "EU", region: "Europe", family: "National Emblem", website: "https://esa.int", description: "PLAnetary Transits and Oscillations of stars. ESA exoplanet hunter. 26 telescopes on one platform. Named after the Greek philosopher. The mission to find Earth-like planets in habitable zones." },
    { name: "LISA Mission", sector: "Mission Program", year: 2035, country: "EU", region: "Europe", family: "National Emblem", website: "https://esa.int", description: "Laser Interferometer Space Antenna. ESA gravitational wave observatory. Three spacecraft in heliocentric orbit. 2.5 million km arms. The most ambitious space science mission ever conceived." },
    { name: "Dragonfly", sector: "Mission Program", year: 2028, country: "USA", region: "United States", family: "National Emblem", website: "https://dragonfly.jhuapl.edu", description: "NASA rotorcraft lander for Saturn's moon Titan. APL-built. Nuclear-powered drone exploring an alien world with a methane atmosphere. The most science-fiction-adjacent NASA mission in development." },
    { name: "Roman Space Telescope", sector: "Mission Program", year: 2027, country: "USA", region: "United States", family: "National Emblem", website: "https://roman.gsfc.nasa.gov", description: "Nancy Grace Roman Space Telescope. NASA's next great observatory. Named after the 'Mother of Hubble.' Wide-field infrared surveyor. Dark energy and exoplanet imaging. The first major NASA mission named after a woman." },
    { name: "SPHEREx", sector: "Mission Program", year: 2025, country: "USA", region: "United States", family: "National Emblem", website: "https://spherex.caltech.edu", description: "Spectro-Photometer for the History of the Universe, Epoch of Reionization and Ices Explorer. NASA all-sky spectroscopic survey. JPL/Caltech. The mission to map the entire sky in 96 spectral bands." },
    { name: "SVOM", sector: "Mission Program", year: 2024, country: "China/France", region: "China", family: "National Emblem", website: "https://svom.cnes.fr", description: "Space Variable Objects Monitor. CNSA/CNES joint gamma-ray burst observatory. French-Chinese bilingual identity. The most significant Sino-European space science collaboration." },
];
