const EXPANSION_3 = [
    // ===================== MORE EO COMPANIES =====================
    { name: "Satellogic Alt", sector: "Earth Observation", year: 2010, country: "Argentina", region: "Latin America", family: "Tech Disruptor", website: "https://satellogic.com", description: "Argentine hyperspectral and multispectral constellation. Buenos Aires-based. Blue/purple. Latin America's most advanced commercial EO company. Sub-meter resolution with hyperspectral capability." },
    { name: "Wyvern", sector: "Earth Observation", year: 2018, country: "Canada", region: "Other", family: "Tech Disruptor", website: "https://wyvern.space", description: "Canadian hyperspectral imaging startup. Edmonton, Alberta. Named after the mythological dragon. Green accent. Agricultural and resource monitoring focus." },
    { name: "UP42", sector: "Earth Observation", year: 2019, country: "Germany", region: "Europe", family: "Tech Disruptor", website: "https://up42.com", description: "Airbus-backed geospatial data marketplace. Berlin-based. Clean, developer-facing API branding. The 'app store' model applied to satellite imagery. Blue/teal." },
    { name: "SkyWatch", sector: "Earth Observation", year: 2014, country: "Canada", region: "Other", family: "Tech Disruptor", website: "https://skywatch.com", description: "Canadian EO data platform. Waterloo, Ontario. API-first approach to satellite imagery distribution. Clean tech branding. Making satellite data accessible to non-expert users." },
    { name: "CloudEO", sector: "Earth Observation", year: 2017, country: "Germany", region: "Europe", family: "Tech Disruptor", website: "https://cloudeo.group", description: "German geospatial data marketplace. Munich-based. Cloud-first satellite data. Clean, modern SaaS aesthetic. The platform layer between satellite operators and end users." },
    { name: "Kayrros", sector: "Earth Observation", year: 2016, country: "France", region: "Europe", family: "Tech Disruptor", website: "https://kayrros.com", description: "French satellite-based environmental intelligence. Climate and energy analytics from space. Paris-based. Green/sustainability accent. Using EO for carbon monitoring and ESG compliance." },
    { name: "Albedo Space", sector: "Earth Observation", year: 2020, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://albedo.com", description: "Very low Earth orbit (VLEO) imaging. 10cm resolution from 250km altitude. Clean, bold branding. Denver-based. Named after the planetary albedo concept. The audacious idea of flying imaging satellites lower than the ISS." },

    // ===================== MORE SATCOM =====================
    { name: "Lynk Global", sector: "Satellite Communications", year: 2015, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://lynk.world", description: "Direct cell-tower-in-space connectivity. Falls Church, Virginia. First company to send a text message from space to an unmodified phone. Blue/teal. The most direct approach to satellite-to-phone." },
    { name: "Mangata Networks", sector: "Satellite Communications", year: 2020, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://mangatanetworks.com", description: "MEO/HEO hybrid broadband constellation. Named after the Swedish word for the reflection of moonlight on water. Purple/gold. The most poetic company name in the satellite communications sector." },
    { name: "SpaceChain", sector: "Other", year: 2017, country: "Singapore", region: "Other", family: "Tech Disruptor", website: "https://spacechain.com", description: "Blockchain infrastructure in space. Singapore-based. Decentralized satellite network. The intersection of cryptocurrency and space technology. Blue/dark branding." },
    { name: "Laser Light Comms", sector: "Satellite Communications", year: 2014, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://laserlightcomms.com", description: "MEO optical communications constellation. HALO (High-Altitude, Low-Orbit) system. Virginia-based. The premise that laser links between satellites can replace fiber optic cables for intercontinental data." },
    { name: "Rivada Networks", sector: "Satellite Communications", year: 2004, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://rivada.com", description: "OuterNET LEO mesh constellation. Decentralized internet infrastructure. Clean, modern branding. The idea of building a 'second internet' in orbit. Washington, D.C.-based." },

    // ===================== MORE DEFENSE/INTELLIGENCE =====================
    { name: "Shield AI", sector: "Defense", year: 2015, country: "USA", region: "United States", family: "Defense Professional", website: "https://shield.ai", description: "Autonomous defense AI. Hivemind autonomy stack. Dark, premium branding. San Diego-based. While primarily drone-focused, the AI autonomy stack extends to space domain awareness applications." },
    { name: "L3Harris Space", sector: "Defense", year: 2019, country: "USA", region: "United States", family: "Defense Professional", website: "https://l3harris.com", description: "Space and Airborne Systems division. Acquired Aerojet Rocketdyne (2023). Blue institutional. The company that now builds both satellites AND the engines that launch them. Melbourne, Florida." },
    { name: "GA-ASI Space", sector: "Defense", year: 1955, country: "USA", region: "United States", family: "Defense Professional", website: "https://ga-asi.com", description: "General Atomics Electromagnetic Systems. Nuclear propulsion research, satellite systems. San Diego-based. Blue/red. The company developing nuclear thermal propulsion for deep space missions." },
    { name: "COMSPOC", sector: "Defense", year: 2017, country: "USA", region: "United States", family: "Defense Professional", website: "https://comspoc.com", description: "Commercial Space Operations Center. AGI/Ansys subsidiary. Space situational awareness analytics. Blue corporate. The commercial alternative to military space tracking." },

    // ===================== MORE INTERNATIONAL AGENCIES =====================
    { name: "CONIDA", sector: "Government Agency", year: 1974, country: "Peru", region: "Latin America", family: "National Emblem", website: "https://conida.gob.pe", description: "Peruvian Space Agency. PNSR-1 satellite heritage. Red/white (Peruvian flag). Lima-based. Andean nation space capability. Focused on Earth observation for agriculture and disaster management." },
    { name: "ABAE", sector: "Government Agency", year: 2008, country: "Venezuela", region: "Latin America", family: "National Emblem", website: "https://abae.gob.ve", description: "Venezuelan Space Agency. VRSS satellites (Venezuelan Remote Sensing Satellites). Blue/red/yellow. Caracas-based. Chinese-built satellites operated by Venezuelan agency." },
    { name: "ACE Bolivia", sector: "Government Agency", year: 2010, country: "Bolivia", region: "Latin America", family: "National Emblem", website: "https://abe.bo", description: "Bolivian Space Agency. Tupak Katari 1 communications satellite (named after indigenous leader). Wiphala flag colors. Chinese-built. The most culturally distinctive satellite naming in Latin America." },
    { name: "SSAU", sector: "Government Agency", year: 1992, country: "Ukraine", region: "Europe", family: "National Emblem", website: "https://ssau.gov.ua", description: "State Space Agency of Ukraine. Zenit rocket heritage. Pivdenmash/Yuzhnoye. Blue/yellow (Ukrainian flag). Dnipro-based. Soviet rocketry heritage now under Ukrainian sovereignty." },
    { name: "POLSA", sector: "Government Agency", year: 2014, country: "Poland", region: "Europe", family: "National Emblem", website: "https://polsa.gov.pl", description: "Polish Space Agency. Warsaw-based. Red/white institutional. ESA member state. Growing European space contributor. Focus on satellite data applications and space sector development." },
    { name: "ROSA", sector: "Government Agency", year: 1991, country: "Romania", region: "Europe", family: "National Emblem", website: "https://rosa.ro", description: "Romanian Space Agency. Bucharest-based. Blue/yellow/red. ESA member. Eastern European space capability. Focus on Earth observation data applications." },
    { name: "BKA", sector: "Government Agency", year: 2007, country: "Belarus", region: "Other", family: "National Emblem", website: "https://bka.by", description: "Belarusian Space Agency. BKA (BelKA) satellite. Minsk-based. Red/green (Belarusian flag). Post-Soviet space capability. Belarus-Russia space cooperation." },
    { name: "ANRT Morocco", sector: "Government Agency", year: 1998, country: "Morocco", region: "Africa", family: "National Emblem", website: "https://anrt.ma", description: "Moroccan space activities under ANRT/Royal Centre for Remote Sensing. Mohammed VI A/B satellites. Red/green (Moroccan flag). North African EO leadership alongside Algeria." },
    { name: "NIHON University Space", sector: "Government Agency", year: 2003, country: "Japan", region: "Japan", family: "Modernist Heritage", website: "https://cubesat.jp", description: "Japanese university CubeSat consortium. XI-IV (2003) among world's first CubeSats. Academic institutional branding. The university labs that proved microsatellites could be built by students." },
    { name: "CIRA", sector: "Government Agency", year: 1984, country: "Italy", region: "Europe", family: "National Emblem", website: "https://cira.it", description: "Italian Aerospace Research Centre. Capua, Italy. Atmospheric reentry research. Blue institutional. The Italian equivalent of DLR or ONERA for aerospace research." },

    // ===================== MORE COMMERCIAL ADDITIONS =====================
    { name: "Spacety Europe", sector: "Earth Observation", year: 2016, country: "Luxembourg", region: "Europe", family: "Tech Disruptor", website: "https://spacety.com", description: "Chinese-founded, Luxembourg-headquartered SAR microsatellite company. Bilingual branding. The first Chinese space company to establish European headquarters. SAR constellation for global monitoring." },
    { name: "Open Cosmos Alt", sector: "Satellite Manufacturing", year: 2014, country: "UK", region: "Europe", family: "Tech Disruptor", website: "https://open-cosmos.com", description: "End-to-end small satellite missions. Harwell, UK. Clean, accessible branding. The company that lets customers order a satellite mission like ordering a service. 'Open' signals democratization." },
    { name: "Rocket Factory Augsburg", sector: "Launch", year: 2018, country: "Germany", region: "Europe", family: "Tech Disruptor", website: "https://rfa.space", description: "German small launch vehicle company. RFA ONE rocket. Augsburg-based. Dark, modern branding. The factory city famous for diesel engines now building rockets." },
    { name: "PLD Space", sector: "Launch", year: 2011, country: "Spain", region: "Europe", family: "Tech Disruptor", website: "https://pldspace.com", description: "Spanish launch company. MIURA rockets (named after the bull breed). First Spanish orbital launcher. Red/dark. Elche-based. The bullfighting metaphor: Spanish cultural identity in rocket naming." },
    { name: "Isar Aerospace", sector: "Launch", year: 2018, country: "Germany", region: "Europe", family: "Tech Disruptor", website: "https://isaraerospace.com", description: "German small launch vehicle company. Spectrum rocket. Munich-based (named after the Isar river). Blue/dark. TU Munich spinoff. One of three German launch startups competing for European small-launch." },
    { name: "EnduroSat", sector: "Satellite Manufacturing", year: 2015, country: "Bulgaria", region: "Europe", family: "Tech Disruptor", website: "https://endurosat.com", description: "Bulgarian satellite bus manufacturer. Sofia-based. Blue/dark. Shared satellite missions. Eastern European NewSpace pioneer. The most unexpected geographic origin alongside Lithuania (NanoAvionics)." },
    { name: "Sateliot", sector: "Satellite Communications", year: 2018, country: "Spain", region: "Europe", family: "Tech Disruptor", website: "https://sateliot.space", description: "Spanish 5G IoT satellite constellation. Barcelona-based. Blue/teal. NB-IoT standard from space. The company extending mobile network standards beyond terrestrial coverage." },
    { name: "GomSpace", sector: "Satellite Manufacturing", year: 2007, country: "Denmark", region: "Europe", family: "Tech Disruptor", website: "https://gomspace.com", description: "Danish nanosatellite manufacturer. Aalborg-based. Clean Nordic design. CubeSat bus platforms. Now part of Momentus. The Scandinavian approach to small satellite engineering." },
    { name: "Astrocast", sector: "Satellite Communications", year: 2014, country: "Switzerland", region: "Europe", family: "Tech Disruptor", website: "https://astrocast.com", description: "Swiss IoT nanosatellite network. Lausanne-based. EPFL heritage. Blue/clean. L-band IoT connectivity. Swiss precision applied to nanosatellite manufacturing." },
    { name: "Spacebel", sector: "Other", year: 1988, country: "Belgium", region: "Europe", family: "Modernist Heritage", website: "https://spacebel.com", description: "Belgian space software company. Liege-based. ESA ground segment software. Blue institutional. The invisible software layer running European space operations." },
    { name: "GMV Aerospace", sector: "Other", year: 1984, country: "Spain", region: "Europe", family: "Modernist Heritage", website: "https://gmv.com", description: "Spanish aerospace technology and software. Madrid-based. Galileo ground segment. Flight dynamics software for ESA. Blue/red corporate. The Spanish engineering firm behind European navigation." },
    { name: "Telespazio Alt", sector: "Satellite Communications", year: 1961, country: "Italy", region: "Europe", family: "Modernist Heritage", website: "https://telespazio.com", description: "Leonardo/Thales joint venture. Italian satellite operations and services. Rome-based. Blue corporate. Fucino Space Centre operations. 60+ years of European satellite services heritage." },
    { name: "OHB Italia", sector: "Satellite Manufacturing", year: 1981, country: "Italy", region: "Europe", family: "Modernist Heritage", website: "https://ohb-italia.it", description: "Italian satellite manufacturer. CGS SpA heritage. Milan-based. Blue institutional. Copernicus Sentinel components. Italian precision engineering for European space missions." },

    // ===================== HISTORICAL MISSIONS & PROGRAMS =====================
    { name: "Ranger Program", sector: "Mission Program", year: 1961, country: "USA", region: "United States", family: "National Emblem", website: "https://nasa.gov", description: "NASA's first lunar impact probe series (1961-1965). Rangers 7-9 returned first close-up images of the Moon. JPL-built. NASA institutional. The reconnaissance missions that mapped Apollo landing sites." },
    { name: "Surveyor Program", sector: "Mission Program", year: 1966, country: "USA", region: "United States", family: "National Emblem", website: "https://nasa.gov", description: "NASA's lunar soft-landing probes (1966-1968). Surveyors 1-7 proved the Moon's surface could support a spacecraft. Hughes Aircraft built. NASA institutional. The scouts that confirmed Apollo could land safely." },
    { name: "Galileo Spacecraft", sector: "Mission Program", year: 1989, country: "USA", region: "United States", family: "National Emblem", website: "https://nasa.gov", description: "NASA Jupiter orbiter and atmospheric probe (1989-2003). Named after Galileo Galilei. First to orbit Jupiter, first atmospheric probe of a gas giant. JPL-built. Circular mission emblem." },
    { name: "Magellan", sector: "Mission Program", year: 1989, country: "USA", region: "United States", family: "National Emblem", website: "https://nasa.gov", description: "NASA Venus radar mapper (1989-1994). Named after Ferdinand Magellan. Mapped 98% of Venus surface. JPL-built. The explorer naming convention: connecting space probes to Age of Exploration navigators." },
    { name: "Stardust Mission", sector: "Mission Program", year: 1999, country: "USA", region: "United States", family: "National Emblem", website: "https://nasa.gov", description: "NASA comet sample return (1999-2011). First comet sample return (Wild 2). Aerogel collection technology. JPL-built. The poetic mission name: literally collecting dust from stars." },
    { name: "SOHO", sector: "Mission Program", year: 1995, country: "USA/EU", region: "United States", family: "National Emblem", website: "https://soho.nascom.nasa.gov", description: "Solar and Heliospheric Observatory. ESA/NASA solar observatory at L1. 30+ years of continuous solar observation. Joint European-American identity. The telescope that watches the Sun 24/7." },
    { name: "SDO", sector: "Mission Program", year: 2010, country: "USA", region: "United States", family: "National Emblem", website: "https://sdo.gsfc.nasa.gov", description: "Solar Dynamics Observatory. NASA's most advanced solar observatory. Captures 1.5 terabytes of solar data daily. Goddard-built. The images SDO produces of solar flares have become the defining visual of solar science." },
    { name: "MESSENGER", sector: "Mission Program", year: 2004, country: "USA", region: "United States", family: "National Emblem", website: "https://nasa.gov", description: "MErcury Surface, Space ENvironment, GEochemistry, and Ranging. First to orbit Mercury (2011-2015). APL-built. NASA's most elaborate acronym: the mission name encodes the science objectives." },
    { name: "Dawn Mission", sector: "Mission Program", year: 2007, country: "USA", region: "United States", family: "National Emblem", website: "https://nasa.gov", description: "NASA asteroid belt explorer. First to orbit two extraterrestrial bodies (Vesta and Ceres). Ion propulsion. JPL-built. The name signals exploring the 'dawn' of the solar system through its oldest objects." },
    { name: "WMAP", sector: "Mission Program", year: 2001, country: "USA", region: "United States", family: "National Emblem", website: "https://map.gsfc.nasa.gov", description: "Wilkinson Microwave Anisotropy Probe. Mapped the cosmic microwave background (2001-2010). Named after David Wilkinson. Goddard-built. The satellite that determined the age, composition, and geometry of the universe." },

    // ===================== FINAL PUSH TO 500 =====================
    { name: "Skylab B", sector: "Mission Program", year: 1973, country: "USA", region: "United States", family: "National Emblem", website: "https://nasa.gov", description: "Unflown backup Skylab station (now in Smithsonian). The most famous spacecraft never launched. NASA institutional. A reminder that space history includes the missions that almost were." },
    { name: "Spacelab", sector: "Mission Program", year: 1983, country: "EU", region: "Europe", family: "National Emblem", website: "https://esa.int", description: "ESA laboratory module flown in Shuttle payload bay (1983-1998). Europe's first permanent presence in human spaceflight. ESA/NASA co-branded. 22 missions. The stepping stone to European ISS modules." },
    { name: "ATV", sector: "Mission Program", year: 2008, country: "EU", region: "Europe", family: "National Emblem", website: "https://esa.int", description: "Automated Transfer Vehicle. ESA's ISS cargo spacecraft (2008-2015). Five missions, each named after a European scientist (Jules Verne, Kepler, etc.). The naming convention honored European scientific heritage." },
    { name: "HTV Kounotori", sector: "Mission Program", year: 2009, country: "Japan", region: "Japan", family: "National Emblem", website: "https://jaxa.jp", description: "JAXA H-II Transfer Vehicle. ISS cargo spacecraft. 'Kounotori' means 'White Stork' (bringing gifts). Japanese poetic naming. JAXA institutional. 9 missions (2009-2020). Succeeded by HTV-X." },
    { name: "Cygnus Spacecraft", sector: "Logo Variant", year: 2013, country: "USA", region: "United States", family: "Modernist Heritage", website: "https://northropgrumman.com", description: "Northrop Grumman ISS cargo spacecraft. Named after the constellation Cygnus (the Swan). Each mission named after a fallen astronaut or space pioneer. The most thoughtful naming convention in active spaceflight." },
    { name: "Dream Chaser", sector: "Logo Variant", year: 2023, country: "USA", region: "United States", family: "Tech Disruptor", website: "https://sierraspace.com", description: "Sierra Space's lifting-body spacecraft. ISS cargo (and eventually crew) vehicle. Blue/sleek branding. The only winged spacecraft in development for ISS servicing. Runway landing capability." },
    { name: "Progress Spacecraft", sector: "Logo Variant", year: 1978, country: "Russia", region: "Russia", family: "National Emblem", website: "https://roscosmos.ru", description: "Russian ISS cargo spacecraft. 'Прогресс' (Progress). 170+ missions since 1978. The most-flown spacecraft design in history. Soyuz-derived. Cyrillic branding. Roscosmos institutional." },
    { name: "Tianzhou", sector: "Logo Variant", year: 2017, country: "China", region: "China", family: "National Emblem", website: "https://cmsa.gov.cn", description: "Chinese cargo spacecraft. '天舟' (Heavenly Vessel). Tiangong station resupply. Chinese calligraphic mission identity. Each mission numbered. CMSA institutional branding." },
    { name: "Vega-E", sector: "Logo Variant", year: 2026, country: "EU", region: "Europe", family: "National Emblem", website: "https://arianespace.com", description: "Next-generation European light launcher. AVIO/ESA development. Methane-fueled upper stage. The evolution of Europe's small launcher lineage from Vega through Vega-C to Vega-E." },
    { name: "Terrier-Orion", sector: "Mission Program", year: 1960, country: "USA", region: "United States", family: "National Emblem", website: "https://nasa.gov", description: "Sounding rocket used by NASA for suborbital research. Military heritage (Terrier missile). The bridge between military rocketry and civilian space science. Still in active use after 60+ years." },
    { name: "Black Brant", sector: "Mission Program", year: 1961, country: "Canada", region: "Other", family: "National Emblem", website: "https://asc-csa.gc.ca", description: "Canadian sounding rocket series. Named after the Black Brant goose. Bristol Aerospace/Magellan built. 1000+ flights. The most successful sounding rocket family in history. Canadian Arctic research heritage." },
    { name: "Electron Missions", sector: "Mission Program", year: 2017, country: "USA/NZ", region: "United States", family: "Tech Disruptor", website: "https://rocketlabusa.com", description: "Rocket Lab's mission identity system. Each Electron flight has a unique name and patch. Names range from technical to whimsical (e.g., 'It's a Test,' 'Still Testing,' 'CAPSTONE'). The most personality-rich mission naming in commercial launch." },
];
